import time
import httpx
from typing import Dict, Any

# Map user-friendly tier names to actual Ollama models
MODEL_TIERS = {
    "cheap": "qwen2.5:0.5b",   # Lightweight, fast model for simple queries
    "strong": "qwen2.5:3b"     # Larger, more capable model for complex queries
}

OLLAMA_URL = "http://localhost:11434/api/generate"

async def call_llm(prompt: str, tier: str = "cheap") -> Dict[str, Any]:
    """
    Dispatches a prompt to the model corresponding to the selected tier,
    measuring response latency and returning a standardized payload.
    """
    # Default to 'cheap' if an invalid tier is passed
    model_name = MODEL_TIERS.get(tier.lower(), MODEL_TIERS["cheap"])

    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False
    }

    start_time = time.perf_counter()

    async with httpx.AsyncClient(timeout=60.0) as client:
        try:
            response = await client.post(OLLAMA_URL, json=payload)
            response.raise_for_status()
            data = response.json()
        except Exception as e:
            raise RuntimeError(f"Error communicating with model '{model_name}': {str(e)}")

    execution_time = round(time.perf_counter() - start_time, 4)

    # Return a standardized dictionary
    return {
        "tier_used": tier,
        "model_used": model_name,
        "response": data.get("response", ""),
        "latency_seconds": execution_time,
        "eval_count": data.get("eval_count", 0)  # Number of tokens generated by Ollama
    }
